### ISSUE TITLE
Cadastro de veículo

### ISSUE THREAD

**Issue by marihellysantini** [gestao-auto/gestao-auto-app#4]

**Comment by rafaelvanat** [comment]
Ao acessar o veículo, a navegação não muda para voltar, continua como sendo o menu. O correto seria retornar a listagem

**Comment by marihellysantini** [comment]
-  Adicionado os inputs das seguintes informações: "unico dono", "data de aquisição primeiro dono" e "data aquisição";
- Corrigida a navegação entre a tela de lista de veículo e cadastro de veículo (comentário do Rafael acima);
- Alterada a cor do modal de cadastro de veículo deixando-o padrão conforme as demais telas;
- Corrigido input de ano, deixando-o datetime podendo selecionar apenas anos.
